# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('key', models.CharField(max_length=32, verbose_name='api key')),
            ],
            options={
                'verbose_name': 'apikey',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set([('user', 'key')]),
        ),
    ]
